### ISSUE TITLE
Screen jumps when loaded

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/accelerant-theme#10]
When you use the full height of the screen with icons in the aside, the native scrollbar is quickly visible on page loads before the custom scrollbar is activated. 

Suggestion, add     
`overflow: hidden !important;`

on .scrollbar

Right now it waits for .ps-container to be attached to the aside before doing it which causes this jumping.

**Comment by RyanThompson** [comment]
Looks like this did it on my end though it was very hard to reproduce: https://github.com/pyrocms/accelerant-theme/commit/94491a6b2d817570d218ed734dfd099809827951
