### ISSUE TITLE
Nested grids capture other grids.

### ISSUE THREAD

**Issue by ddnetters** [pyrocms/accelerant-theme#17]
When you have a nested grid with the following structure:
```
Block
    Founders
        Founder
        Founder
        Founder
```
And you try to add another grid to `Block` it'll be put under the `Founders` grid instead of under `Blocks`.

**Comment by RyanThompson** [comment]
Hey man - all issues need to go into main repository: https://pyrocms.com/documentation/pyrocms/v3.1#contributing/bug-reports

**Comment by RyanThompson** [comment]
I believe this has been remedied.
