### ISSUE TITLE
Reduce height of aside navigation rows

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/accelerant-theme#7]
The navigation easily use more than the screens available height. Esp on laptos/notebooks.

I think we should make the icons smaller, as well as the font size and reduce the margins.

To me, i think the font size could be 16px, and the line-height 24px, margins 10.

**Comment by RyanThompson** [comment]
No way! lol

**Comment by RyanThompson** [comment]
Im scared of tight spaces.

**Comment by RyanThompson** [comment]
And I have bad eyes.

**Comment by RyanThompson** [comment]
That's why I keep cats around. They lead me around.
