### ISSUE TITLE
Refactor aside to make it easier to use

### ISSUE THREAD

**Issue by designbywilliam** [pyrocms/accelerant-theme#8]
I have some issues personally with the current aside.

1. The font is way too big. This causes issues i reported just now about the screens available height quickly getting used. It also causes a problem when you got your own modules with a little longer names since the width of the left side is not really wide enough.
2. I have a hard time remembering what the icons stand for. So i find myself having to guess or click on the menu button to expand the name and then click again. Both scenarios are frustrating. I would prefer we skip the icons, and use text only. Easiest solution would probably be on XL width, just add more width to the left side and show text there instead of icons. You got enough room on those screen resolutions. And then keep the icons for pads/mobiles as is.

**Comment by RyanThompson** [comment]
This is something we're putting through client trials to see what we come up with. We can discuss after things have been properly beaten up ^_^
